### ISSUE TITLE
Suggestion: MPRIS for Macos

### ISSUE THREAD

**Issue by 741nfect** [raitonoberu/sptlrx#37] opened 2024-01-11 13:53 UTC
Im sure many ncspot (MPRIS) users like me is waiting for mac support. This would be crazy!

At this moment, when i edit the config to work with mpris on my m1 mac, i get the below error:
Error: couldn't load player: darwin is not supported

**Comment by raitonoberu** [comment] 2024-01-11 15:09
Duplicate of #17. As far as I can tell, MPRIS does not work on macOS.

[1] https://www.reddit.com/r/swift/comments/nvjyy0/is_there_an_equivalent_for_mpris_in_macos/
[2] https://stackoverflow.com/questions/71952443/how-to-install-playerctl-in-mac

**Closed by raitonoberu** 2024-01-11 15:09 UTC
